import fs from 'node:fs';
import {familyHistoryFor, verifiedRecordsFor, evidenceLabels} from './src/family-history-archive.js';

const base='https://metcalfe-kavanagh-family-site.vercel.app';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=o=>JSON.stringify(o).replace(/</g,'\\u003c');
const people=[['william-metcalfe','William Metcalfe'],['john-medcalf-enoch-son','John Metcalfe'],['edward-medcalf','Edward Metcalfe'],['mary-kavanagh','Mary Kavanagh'],['anthony-medcalf','Enoch Metcalfe'],['anthony-metcalf-enoch-father','Anthony Metcalfe'],['sarah-jane-byrne','Sarah Jane Metcalfe']];
const link=(url,label)=>`<a href="${esc(url)}">${esc(label)}</a>`;
const chapters=items=>items.map((c,i)=>`<section id="chapter-${i+1}"><h2>${esc(c.title)}</h2><p class="evidence">${esc(evidenceLabels[c.evidence]||'Family Archive')}</p><p>${esc(c.text)}</p>${c.recordUrl?`<p>${link(c.recordUrl,c.recordLabel||'View source record')}</p>`:''}${c.sources?.length?`<ul>${c.sources.map(s=>`<li>${link(s.url,s.label)}</li>`).join('')}</ul>`:''}</section>`).join('');
function page(path,title,description,body,extra={}) {
 const url=base+path;
 const schema={'@context':'https://schema.org','@type':'Article',headline:title,description,url,mainEntityOfPage:url,isPartOf:{'@type':'WebSite',name:'Metcalfe & Kavanagh Family History',url:base+'/'},...extra};
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Metcalfe &amp; Kavanagh Family History</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${url}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="article"><meta property="og:url" content="${url}"><meta property="og:image" content="${base}/altadore-garden.jpeg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/history.css"><script type="application/ld+json">${json(schema)}</script></head><body><header><a href="/">Metcalfe &amp; Kavanagh Family</a><nav aria-label="Main navigation"><a href="/history/">Historical Stories &amp; Research</a><a href="/?view=tree">Family Tree</a><a href="/?view=sources">Sources</a></nav></header><main><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/history/">Historical Research</a></nav><article><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p>${body}</article></main><footer><p>Researched and assembled by Paul Butler. ${link('/?view=about','Contact us with a family connection, source or correction')}.</p><p>${link('/?view=evidence','How we assess evidence')} · ${link('https://www.youwho.ie/medcalf.html','YouWho — supporting family research')}</p></footer></body></html>`;
 const target='dist'+path+'index.html';fs.mkdirSync(target.slice(0,target.lastIndexOf('/')),{recursive:true});fs.writeFileSync(target,html);
}
const paths=[];
for(const [id,name] of people){
 const history=familyHistoryFor({id});if(!history)throw new Error('Missing history: '+id);
 const path=`/history/${id}/`;paths.push(path);
 const title=id==='william-metcalfe'?'William Metcalfe — From Gallipoli to the Irish National Army':name;
 const records=verifiedRecordsFor({id});
 const docs=history.documents||[];
 const body=`<p>${link('/?view=profile&id='+id,'Explore the full family profile and archive')}</p>${id==='william-metcalfe'?`<aside>${link('/history/5th-royal-inniskilling-fusiliers/','Read the 5th Royal Inniskilling Fusiliers battalion history')}<p>William is recorded as W. Medcalf in contemporary First World War newspapers. His Gallipoli service is documented; later battalion campaigns are identified as historical context.</p></aside>`:''}<nav class="contents" aria-label="Article contents"><h2>In this story</h2><ul>${history.chapters.map((c,i)=>`<li>${link('#chapter-'+(i+1),c.title)}</li>`).join('')}<li><a href="#sources">Documents and sources</a></li></ul></nav>${chapters(history.chapters)}<section id="sources"><h2>Documents and sources</h2>${records.map(r=>`<p><strong>${esc(r.title)}</strong> — ${esc(r.detail)}. ${link(r.url,r.linkLabel||'View record')}</p>`).join('')}${docs.map(d=>`<section><h3>${esc(d.title)}</h3><p class="evidence">${esc(d.publication||'Family Archive')}${d.date?' · '+esc(d.date):''} · ${esc(evidenceLabels[d.evidence]||'Family Archive')}</p><p>${esc(d.context||d.caption||'')}</p>${d.provenance?`<p class="source">${esc(d.provenance)}</p>`:''}${d.transcription?`<details><summary>Read transcription</summary><p class="transcription">${esc(d.transcription)}</p></details>`:''}</section>`).join('')}</section>${history.notes?.length?`<section><h2>Research notes</h2><ul>${history.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></section>`:''}`;
 page(path,title,history.summary,body,{about:{'@type':'Person',name,...(id==='william-metcalfe'?{alternateName:['William Medcalf','W. Medcalf'],birthDate:'1896-05-06',deathDate:'1940'}:{})}});
}
const william=familyHistoryFor({id:'william-metcalfe'});
const campaign=william.chapters.filter(c=>c.title.startsWith('The 5th Battalion')||c.title.startsWith('Egypt and Palestine')||c.title.startsWith('France and the Hindenburg'));
if(campaign.length!==3)throw new Error('Battalion chapters missing');
paths.push('/history/5th-royal-inniskilling-fusiliers/');
page(paths.at(-1),'5th Royal Inniskilling Fusiliers — First World War Battalion History','The battalion’s movements from Gallipoli to Macedonia, Palestine and France, with sources and a clear distinction between unit history and William Metcalfe’s documented service.',`<aside><p>William’s newspaper letter confirms 5th Battalion service at Gallipoli. A battalion’s later movements do not alone prove his presence in every campaign.</p>${link('/history/william-metcalfe/','Read William Metcalfe’s story')}</aside>${chapters(campaign)}`);
paths.unshift('/history/');
page('/history/','Historical Stories & Research','Sourced family and local history from Blackrock, Stillorgan and Altidore, including William Metcalfe’s military service and the Metcalfe and Kavanagh families.',`<section class="featured"><h2>${link('/history/william-metcalfe/','William Metcalfe — From Gallipoli to the Irish National Army')}</h2><p>${esc(william.summary)}</p></section><h2>Explore the archive</h2><div class="cards">${people.slice(1).map(([id,name])=>`<section><h3>${link('/history/'+id+'/',name)}</h3><p>${esc(familyHistoryFor({id}).summary)}</p></section>`).join('')}<section><h3>${link('/history/5th-royal-inniskilling-fusiliers/','5th Royal Inniskilling Fusiliers')}</h3><p>Battalion movements, battles and historical sources, 1914–1919.</p></section></div>`);
const old=fs.readFileSync('src/sitemap.xml','utf8').replace(/\s*<url><loc>[^<]*\?view=(ask|visitors)[^<]*<\/loc><\/url>/g,'');
fs.writeFileSync('dist/sitemap.xml',old.replace('</urlset>',paths.map(p=>`  <url><loc>${base+p}</loc></url>`).join('\n')+'\n</urlset>'));
