import { familyHistoryFor, verifiedRecordsFor } from '/family-history-archive.js?v=20260914-william-boxing-1';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TABLES=['people','parent_child','couples','person_relationships','media','media_people','research_sources','research_source_people','stories','guestbook_entries','guestbook_contacts','profile_change_log','site_stats'];

export async function mountAdminQuality(before,{db,people,media,researchSources}){
  const host=document.createElement('section');host.className='admin-quality-stack';before.before(host);
  const linked=new Map();
  for(const source of researchSources)for(const row of source.research_source_people||[]){if(!linked.has(row.person_id))linked.set(row.person_id,[]);linked.get(row.person_id).push(source)}
  const rows=people.map(p=>{
    const staticRecords=verifiedRecordsFor(p),sources=linked.get(p.id)||[],types=new Set([...staticRecords.map(r=>r.title.toLowerCase()),...sources.map(s=>String(s.record_type||'').toLowerCase())]);
    const has=x=>[...types].some(t=>t.includes(x));
    const gaps=[];if(!has('birth'))gaps.push('birth');if(!has('death')&&!p.death_date_text)gaps.push('death');if(!has('census'))gaps.push('census');if(!p.biography&&!familyHistoryFor(p))gaps.push('life story');if(!media.some(m=>m.person_id===p.id&&m.is_profile_photo))gaps.push('photo');
    return{p,gaps,evidence:staticRecords.length+sources.length};
  }).sort((a,b)=>b.gaps.length-a.gaps.length||a.p.name.localeCompare(b.p.name));
  const complete=rows.filter(r=>!r.gaps.length).length,withStories=rows.filter(r=>!r.gaps.includes('life story')).length,withEvidence=rows.filter(r=>r.evidence).length;
  host.innerHTML=`<section class="card admin-protection"><span class="source-type">Archive protection</span><h2>Backup &amp; Recovery</h2><p>Download a dated JSON backup of the family database and a manifest of every stored media file. Keep occasional copies away from the website account.</p><div class="admin-protection-actions"><button id="downloadArchiveBackup" class="btn" type="button">Download full backup</button><label class="admin-secondary backup-check">Validate a backup file<input id="validateArchiveBackup" type="file" accept="application/json,.json" hidden></label></div><div id="backupStatus" class="status" hidden></div><p class="muted"><small>The original photographs and documents remain in Supabase Storage. Their bucket names and paths are included so the files can be recovered or exported separately.</small></p></section><section class="card research-coverage"><span class="source-type">Research planning</span><h2>Family Record Coverage</h2><p class="muted">A private research queue showing where profiles would benefit from further evidence or content.</p><div class="coverage-summary"><div><strong>${people.length}</strong><span>people</span></div><div><strong>${complete}</strong><span>complete profiles</span></div><div><strong>${withEvidence}</strong><span>with linked evidence</span></div><div><strong>${withStories}</strong><span>with a life story</span></div></div><table class="coverage-table"><thead><tr><th>Person</th><th>Evidence</th><th>Suggested next work</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a href="/?view=profile&id=${encodeURIComponent(r.p.id)}" target="_blank" rel="noopener">${esc(r.p.name)}</a></td><td>${r.evidence}</td><td class="${r.gaps.length?'coverage-gaps':''}">${r.gaps.length?esc(r.gaps.join(' · ')):'Well covered'}</td></tr>`).join('')}</tbody></table></section>`;
  const status=host.querySelector('#backupStatus');
  host.querySelector('#downloadArchiveBackup').onclick=async e=>{const button=e.currentTarget;button.disabled=true;status.hidden=false;status.className='status';status.textContent='Preparing database backup…';try{const tables={};for(const name of TABLES){const {data,error}=await db.from(name).select('*');if(error)throw new Error(`${name}: ${error.message}`);tables[name]=data||[]}const payload={format:'metcalfe-kavanagh-family-backup',version:1,created_at:new Date().toISOString(),site:'https://metcalfe-kavanagh-family-site.vercel.app/',tables,media_manifest:(tables.media||[]).map(m=>({id:m.id,bucket:m.bucket_name||'family-media',storage_path:m.storage_path,thumbnail_path:m.thumbnail_path||null,original_filename:m.original_filename||null}))};const body=JSON.stringify(payload,null,2),blob=new Blob([body],{type:'application/json'}),a=document.createElement('a'),day=payload.created_at.slice(0,10);a.href=URL.createObjectURL(blob);a.download=`metcalfe-kavanagh-backup-${day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent=`Backup created: ${tables.people.length} people, ${tables.media.length} media records and ${tables.research_sources.length} research sources.`}catch(error){status.className='status error';status.textContent=`Backup could not be completed. ${error.message}`}finally{button.disabled=false}};
  host.querySelector('#validateArchiveBackup').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;status.hidden=false;try{const data=JSON.parse(await file.text());if(data.format!=='metcalfe-kavanagh-family-backup'||data.version!==1||!Array.isArray(data.tables?.people)||!Array.isArray(data.media_manifest))throw new Error('This is not a complete family archive backup.');status.className='status';status.textContent=`Backup valid — created ${new Date(data.created_at).toLocaleString('en-IE')}, containing ${data.tables.people.length} people and ${data.media_manifest.length} media references.`}catch(error){status.className='status error';status.textContent=`Backup validation failed. ${error.message}`}finally{e.target.value=''}};
}
