const cfg=window.__APP_CONFIG__||{};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const header=(t,s)=>`<section class="heritage"><div class="wrap"><h1>${esc(t)}</h1><p>${esc(s)}</p></div></section>`;
const mobileMenu=document.getElementById('mobileMenu');
document.getElementById('menuButton').onclick=()=>mobileMenu.classList.toggle('open');
document.getElementById('bottomMenu').onclick=e=>{e.preventDefault();mobileMenu.classList.toggle('open');scrollTo({top:0,behavior:'smooth'})};

async function getSession(){const {data}=await db.auth.getSession();return data.session}
async function isAdmin(){const {data,error}=await db.from('site_admins').select('email').limit(1);return !error&&(data||[]).length>0}

function renderLogin(){
  app.innerHTML=header('Administration','Secure editing for the Metcalfe & Kavanagh family archive.')+`<section class="section"><div class="wrap"><div class="card admin-login"><h2>Admin sign in</h2><p class="muted">Enter your approved admin email address. We’ll send you a secure sign-in link.</p><form id="adminLoginForm"><div class="field"><label for="adminEmail"><strong>Email address</strong></label><input id="adminEmail" type="email" autocomplete="email" required placeholder="you@example.com"></div><div id="loginStatus" class="status" hidden></div><button class="btn" type="submit">Send secure sign-in link</button></form></div></div></section>`;
  const form=document.getElementById('adminLoginForm'),status=document.getElementById('loginStatus');
  form.addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('adminEmail').value.trim();status.hidden=false;status.className='status';status.textContent='Sending sign-in link…';const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/?view=admin`}});if(error){status.className='status error';status.textContent=error.message}else{status.textContent='Check your email and tap the secure sign-in link. You’ll return here automatically.'}});
}

async function renderAdmin(session){
  if(!(await isAdmin())){app.innerHTML=header('Administration','This account does not have editing access.')+`<section class="section"><div class="wrap"><div class="status error">Signed in as ${esc(session.user.email||'this account')}, but this email is not an approved site administrator.</div><button id="adminSignOut" class="btn">Sign out</button></div></section>`;document.getElementById('adminSignOut').onclick=async()=>{await db.auth.signOut();location.reload()};return}
  const [{data:ps,error:pe},{data:med,error:me}]=await Promise.all([db.from('people').select('*').order('name'),db.from('media').select('*').eq('media_type','photo').order('created_at',{ascending:false})]);
  if(pe||me)throw pe||me;
  const people=ps||[],media=med||[];
  let currentId=people[0]?.id||null;
  const profileFor=id=>media.find(m=>m.person_id===id&&m.is_profile_photo);
  const mediaUrl=m=>m?`${cfg.SUPABASE_URL}/storage/v1/object/public/${m.bucket_name||'family-media'}/${m.storage_path}`:'';
  app.innerHTML=header('Administration','Edit family profiles and profile photographs.')+`<section class="section"><div class="wrap"><div class="admin-toolbar"><div><strong>Signed in:</strong> ${esc(session.user.email||'')}</div><button id="adminSignOut" class="admin-secondary" type="button">Sign out</button></div><div class="admin-shell"><aside class="card admin-sidebar"><label for="adminPersonSearch"><strong>Family members</strong></label><input id="adminPersonSearch" class="admin-search" type="search" placeholder="Search names"><div id="adminPeopleList" class="admin-people-list"></div></aside><section id="adminEditor" class="card admin-editor"></section></div></div></section>`;
  const list=document.getElementById('adminPeopleList'),editor=document.getElementById('adminEditor'),search=document.getElementById('adminPersonSearch');
  document.getElementById('adminSignOut').onclick=async()=>{await db.auth.signOut();location.href='/?view=admin'};
  const renderList=()=>{const q=search.value.trim().toLowerCase();list.innerHTML=people.filter(p=>!q||p.name.toLowerCase().includes(q)).map(p=>`<button type="button" class="admin-person ${p.id===currentId?'active':''}" data-id="${esc(p.id)}"><span>${esc(p.name)}</span><small>${esc(p.birth_date_text||'')}</small></button>`).join('')||'<p class="muted">No matching names.</p>'};
  const val=(p,k)=>esc(p[k]||'');
  const renderEditor=()=>{const p=people.find(x=>x.id===currentId);if(!p){editor.innerHTML='<p>No family member selected.</p>';return}const prof=profileFor(p.id);editor.innerHTML=`<div class="admin-editor-head"><div><h2>${esc(p.name)}</h2><p class="muted">Edit this person’s family-history record.</p></div><a class="admin-view-link" href="/?view=profile&id=${encodeURIComponent(p.id)}" target="_blank">View profile ↗</a></div><div class="admin-photo-row"><div class="admin-photo-preview">${prof?`<img src="${mediaUrl(prof)}" alt="${esc(p.name)}">`:`<span>${esc((p.initials||p.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')).toUpperCase())}</span>`}</div><div><h3>Profile photo / avatar</h3><p class="muted">Upload a JPG, PNG or WebP photo. The newest upload becomes the profile image.</p><input id="profilePhoto" type="file" accept="image/jpeg,image/png,image/webp"><button id="uploadProfilePhoto" type="button" class="admin-secondary">Upload profile photo</button><div id="photoStatus" class="status" hidden></div></div></div><form id="personEditForm"><div class="form-grid"><div class="field full"><label><strong>Full name</strong></label><input name="name" value="${val(p,'name')}" required></div><div class="field"><label>Given names</label><input name="given_names" value="${val(p,'given_names')}"></div><div class="field"><label>Surname</label><input name="surname" value="${val(p,'surname')}"></div><div class="field"><label>Birth date</label><input name="birth_date_text" value="${val(p,'birth_date_text')}" placeholder="e.g. 10 Jun 1897"></div><div class="field"><label>Birth place</label><input name="birth_place" value="${val(p,'birth_place')}"></div><div class="field"><label>Death date</label><input name="death_date_text" value="${val(p,'death_date_text')}"></div><div class="field"><label>Death place</label><input name="death_place" value="${val(p,'death_place')}"></div><div class="field"><label>Relationship label</label><input name="relation_label" value="${val(p,'relation_label')}" placeholder="e.g. Grandmother"></div><div class="field"><label>Family line</label><input name="family_line" value="${val(p,'family_line')}"></div><div class="field full"><label>Biography / life story</label><textarea name="biography" rows="7">${val(p,'biography')}</textarea></div><div class="field full"><label>Research notes</label><textarea name="notes" rows="5">${val(p,'notes')}</textarea></div><div class="field"><label class="admin-check"><input name="featured" type="checkbox" ${p.featured?'checked':''}> Featured person</label></div></div><div id="saveStatus" class="status" hidden></div><button class="btn admin-save" type="submit">Save changes</button></form>`;
    const form=editor.querySelector('#personEditForm'),saveStatus=editor.querySelector('#saveStatus');
    form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const payload={name:String(fd.get('name')||'').trim(),given_names:String(fd.get('given_names')||'').trim()||null,surname:String(fd.get('surname')||'').trim()||null,birth_date_text:String(fd.get('birth_date_text')||'').trim()||null,birth_place:String(fd.get('birth_place')||'').trim()||null,death_date_text:String(fd.get('death_date_text')||'').trim()||null,death_place:String(fd.get('death_place')||'').trim()||null,relation_label:String(fd.get('relation_label')||'').trim()||null,family_line:String(fd.get('family_line')||'').trim()||null,biography:String(fd.get('biography')||'').trim()||null,notes:String(fd.get('notes')||'').trim()||null,featured:form.elements.featured.checked,updated_at:new Date().toISOString()};saveStatus.hidden=false;saveStatus.className='status';saveStatus.textContent='Saving…';const {data,error}=await db.from('people').update(payload).eq('id',p.id).select().single();if(error){saveStatus.className='status error';saveStatus.textContent=error.message;return}Object.assign(p,data);saveStatus.textContent='Changes saved successfully.';renderList();});
    editor.querySelector('#uploadProfilePhoto').onclick=async()=>{const input=editor.querySelector('#profilePhoto'),status=editor.querySelector('#photoStatus'),file=input.files?.[0];status.hidden=false;if(!file){status.className='status error';status.textContent='Choose a photo first.';return}if(file.size>10*1024*1024){status.className='status error';status.textContent='Please choose an image under 10 MB.';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){status.className='status error';status.textContent='Please use JPG, PNG or WebP.';return}status.className='status';status.textContent='Uploading profile photo…';const ext=file.name.split('.').pop().toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`profiles/${p.id}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await db.storage.from('family-media').upload(path,file,{contentType:file.type,upsert:false});if(ue){status.className='status error';status.textContent=ue.message;return}const {error:clearError}=await db.from('media').update({is_profile_photo:false}).eq('person_id',p.id).eq('is_profile_photo',true);if(clearError){status.className='status error';status.textContent=clearError.message;return}const {data:newMedia,error:ie}=await db.from('media').insert({person_id:p.id,media_type:'photo',title:`Profile photo - ${p.name}`,storage_path:path,bucket_name:'family-media',mime_type:file.type,is_profile_photo:true}).select().single();if(ie){status.className='status error';status.textContent=ie.message;return}media.unshift(newMedia);status.textContent='Profile photo updated successfully.';renderEditor();};
  };
  list.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;currentId=b.dataset.id;renderList();renderEditor();scrollTo({top:document.querySelector('.heritage').offsetHeight,behavior:'smooth'})});
  search.addEventListener('input',renderList);renderList();renderEditor();
}

(async()=>{try{if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY)throw new Error('Supabase configuration is missing.');const session=await getSession();if(!session)renderLogin();else await renderAdmin(session)}catch(e){console.error(e);app.innerHTML=header('Administration','The admin area could not load.')+`<section class="section"><div class="wrap"><div class="status error">${esc(e.message||e)}</div></div></section>`}})();
