const cfg=window.__APP_CONFIG__||{};
const app=document.getElementById('app');
const qs=new URLSearchParams(location.search);const view=qs.get('view')||'home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=p=>(p.name||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const year=s=>{const m=String(s||'').match(/(18|19|20)\d{2}/);return m?m[0]:''};
const years=p=>{const a=year(p.birth_date_text),b=year(p.death_date_text);return a||b?`${a||'?'} – ${b||''}`:''};
const header=(t,s)=>`<section class="heritage"><div class="wrap"><h1>${esc(t)}</h1><p>${esc(s)}</p></div></section>`;
if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY){app.innerHTML=header('Site configuration needed','The family archive is ready, but the Supabase connection has not yet been configured in Vercel.')+'<section class="section"><div class="wrap"><div class="status error">Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY.</div></div></section>';throw new Error('Missing Supabase config')}
const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
async function people(){const {data,error}=await db.from('people').select('*').order('name');if(error)throw error;return data||[]}
async function media(){const {data}=await db.from('media').select('*').order('created_at',{ascending:false});return data||[]}
async function rels(){const [{data:r},{data:c}]=await Promise.all([db.from('parent_child').select('*'),db.from('couples').select('*')]);return{r:r||[],c:c||[]}}
function personCard(p){return `<a class="card person" href="/?view=profile&id=${p.id}"><div class="avatar">${esc(initials(p))}</div><div><strong>${esc(p.name)}</strong><div class="muted">${esc(years(p)||p.relation_label||'Family member')}</div>${p.birth_place?`<small>${esc(p.birth_place)}</small>`:''}</div></a>`}
async function home(){const ps=await people();const featured=['William Metcalfe','Mary Kavanagh','Enoch Medcalf','Mary King'].map(n=>ps.find(p=>p.name===n)).filter(Boolean);app.innerHTML=`<section class="hero"><div class="wrap"><h1>The Metcalfe & Kavanagh Family</h1><p>Our Family History • Our Stories • Our Heritage</p><a class="btn" href="/?view=tree">Explore Our Family Tree</a></div></section><section class="section"><div class="wrap"><div class="homegrid"><a class="feature" href="/?view=tree"><span class="ico">🌳</span><strong>Family Tree</strong><small>Explore generations and relationships</small></a><a class="feature" href="/?view=people"><span class="ico">👥</span><strong>People</strong><small>Browse family profiles</small></a><a class="feature" href="/?view=gallery&type=document"><span class="ico">📜</span><strong>Documents</strong><small>Official and historical records</small></a><a class="feature" href="/?view=gallery"><span class="ico">🗂️</span><strong>Photos &amp; Documents</strong><small>Explore the family archive</small></a></div><div class="subgrid"><a class="feature" href="/?view=places"><span class="ico">📍</span><strong>Places</strong><small>Locations connected to the family</small></a><a class="feature" href="/?view=timeline"><span class="ico">🕰️</span><strong>Timeline</strong><small>The family story in date order</small></a><a class="feature" href="/?view=stories"><span class="ico">✦</span><strong>Stories</strong><small>Lives, memories and family history</small></a><a class="feature" href="/?view=visitors"><span class="ico">✒️</span><strong>Visitors’ Book</strong><small>Sign your name or share a family connection</small></a></div></div></section><section class="section" style="background:#eef3ee"><div class="wrap"><h2>Featured Ancestors</h2><div class="person-grid">${featured.map(personCard).join('')}</div></div></section>`}
async function peopleView(){const ps=await people();app.innerHTML=header('People','Meet the people whose lives form our family history.')+`<section class="section"><div class="wrap"><div class="person-grid">${ps.map(personCard).join('')}</div></div></section>`}
async function placesView(){const ps=await people(),map={};ps.forEach(p=>[['Birth',p.birth_place],['Death',p.death_place]].forEach(([type,place])=>{if(place)(map[place]??=[]).push({p,type})}));app.innerHTML=header('Places','Explore the towns and places connected with the family.')+`<section class="section"><div class="wrap places">${Object.entries(map).sort((a,b)=>b[1].length-a[1].length).map(([pl,items])=>`<div class="card place"><div style="font-size:28px">📍</div><h2>${esc(pl)}</h2><p class="muted">${items.length} recorded family connection${items.length===1?'':'s'}</p>${items.map(x=>`<p><a href="/?view=profile&id=${x.p.id}"><strong>${esc(x.p.name)}</strong></a> — ${x.type}</p>`).join('')}</div>`).join('')||'<div class="card">No places have been recorded yet.</div>'}</div></section>`}
async function timelineView(){const ps=await people(),rr=await rels(),by=Object.fromEntries(ps.map(p=>[p.id,p])),events=[];ps.forEach(p=>{if(p.birth_date_text)events.push({y:+year(p.birth_date_text)||9999,d:p.birth_date_text,t:`Birth of ${p.name}`,p:p.birth_place});if(p.death_date_text)events.push({y:+year(p.death_date_text)||9999,d:p.death_date_text,t:`Death of ${p.name}`,p:p.death_place})});rr.c.forEach(c=>{if(c.marriage_date_text)events.push({y:+year(c.marriage_date_text)||9999,d:c.marriage_date_text,t:`Marriage of ${by[c.person1_id]?.name||'Unknown'} and ${by[c.person2_id]?.name||'Unknown'}`,p:c.marriage_place})});events.sort((a,b)=>a.y-b.y);app.innerHTML=header('Timeline','Follow the family story through births, marriages and deaths.')+`<section class="section"><div class="wrap"><div class="timeline">${events.map(e=>`<div class="card event"><div class="year">${esc(e.d)}</div><h3>${esc(e.t)}</h3>${e.p?`<p class="muted">📍 ${esc(e.p)}</p>`:''}</div>`).join('')}</div></div></section>`}
async function storiesView(){const {data,error}=await db.from('stories').select('*').order('created_at',{ascending:false});if(error)throw error;app.innerHTML=header('Stories','Family memories, recollections and historical stories.')+`<section class="section"><div class="wrap"><div class="person-grid">${(data||[]).map(s=>`<article class="card story"><div style="font-size:28px">✦</div><h2>${esc(s.title||'Family story')}</h2><p>${esc(s.summary||s.body||'')}</p></article>`).join('')||'<div class="card story">No stories have been added yet.</div>'}</div></div></section>`}
async function recordsView(){const med=(await media()).filter(m=>m.media_type==='document');app.innerHTML=header('Records','Historical documents and official records connected to the family.')+`<section class="section"><div class="wrap records">${med.map(m=>{const u=`${cfg.SUPABASE_URL}/storage/v1/object/public/family-media/${m.storage_path}`;return `<a class="card record" target="_blank" href="${u}"><div style="font-size:42px">📜</div><h2>${esc(m.title||'Family record')}</h2><p>${esc(m.description||'Open document')}</p></a>`}).join('')||'<div class="card record">No records have been added yet.</div>'}</div></section>`}
async function galleryView(){const med=(await media()).filter(m=>m.media_type==='photo');app.innerHTML=header('Gallery','Family photographs preserved across the generations.')+`<section class="section"><div class="wrap media-grid">${med.map(m=>{const u=`${cfg.SUPABASE_URL}/storage/v1/object/public/family-media/${m.storage_path}`;return `<a class="card" target="_blank" href="${u}"><img src="${u}"><h3>${esc(m.title||'Family photograph')}</h3><p class="muted">${esc(m.description||'')}</p></a>`}).join('')||'<div class="card">No photographs have been added yet.</div>'}</div></section>`}
async function profile(){
  const id=qs.get('id'),ps=await people(),p=ps.find(x=>x.id===id);
  if(!p){app.innerHTML=header('Person not found','The requested family profile could not be found.');return}
  const rr=await rels(),by=Object.fromEntries(ps.map(x=>[x.id,x])),parents=rr.r.filter(x=>x.child_id===p.id).map(x=>by[x.parent_id]).filter(Boolean),children=[...new Set(rr.r.filter(x=>x.parent_id===p.id).map(x=>x.child_id))].map(id=>by[id]).filter(Boolean),spouses=rr.c.filter(x=>x.person1_id===p.id||x.person2_id===p.id).map(x=>by[x.person1_id===p.id?x.person2_id:x.person1_id]).filter(Boolean),bits=[];
  if(p.birth_date_text||p.birth_place)bits.push(`${p.name} was born${p.birth_date_text?' on '+p.birth_date_text:''}${p.birth_place?' in '+p.birth_place:''}.`);if(parents.length)bits.push(`${parents.length>1?'Their recorded parents are':'Their recorded parent is'} ${parents.map(x=>x.name).join(' and ')}.`);if(spouses.length)bits.push(`${p.name} is recorded as the spouse of ${spouses.map(x=>x.name).join(' and ')}.`);if(children.length)bits.push(`Recorded children include ${children.map(x=>x.name).join(', ')}.`);if(p.death_date_text||p.death_place)bits.push(`${p.name} died${p.death_date_text?' on '+p.death_date_text:''}${p.death_place?' in '+p.death_place:''}.`);
  const [{data:allMedia},{data:linked}]=await Promise.all([db.from('media').select('*').order('created_at',{ascending:false}),db.from('media_people').select('media_id').eq('person_id',p.id)]),linkedIds=new Set((linked||[]).map(x=>x.media_id)),med=(allMedia||[]).filter(m=>m.person_id===p.id||linkedIds.has(m.id)),prof=med.find(m=>m.is_profile_photo&&m.media_type==='photo'),mediaUrl=m=>`${cfg.SUPABASE_URL}/storage/v1/object/public/${m.bucket_name||'family-media'}/${m.storage_path}`,img=prof?mediaUrl(prof):null,photos=med.filter(m=>m.media_type==='photo'&&!m.is_profile_photo),documents=med.filter(m=>m.media_type==='document');
  const cards=list=>list.map(m=>`<a class="profile-media-card" target="_blank" rel="noopener" href="${mediaUrl(m)}">${m.media_type==='photo'?`<img src="${mediaUrl(m)}" alt="${esc(m.title||'Family photograph')}" loading="lazy">`:'<span class="profile-doc-icon">📜</span>'}<div><strong>${esc(m.title||m.original_filename||(m.media_type==='photo'?'Family photograph':'Family document'))}</strong><small>${esc([m.category,m.event_date_text].filter(Boolean).join(' • '))}</small></div></a>`).join('');
  app.innerHTML=header(p.name,'Family profile')+`<section class="section"><div class="wrap profile"><div>${img?`<img class="profile-photo" src="${img}" alt="${esc(p.name)}">`:`<div class="profile-photo">${esc(initials(p))}</div>`}</div><div><div class="profile-hero"><h1>${esc(p.name)}</h1><p class="muted">${esc(years(p))}</p><div class="facts"><div class="fact"><strong>Born</strong><br>${esc(p.birth_date_text||'Not recorded')}${p.birth_place?`<br><span class="muted">${esc(p.birth_place)}</span>`:''}</div><div class="fact"><strong>Died</strong><br>${esc(p.death_date_text||'Not recorded')}${p.death_place?`<br><span class="muted">${esc(p.death_place)}</span>`:''}</div></div></div><div class="card summary"><h2>At a glance</h2><p>${esc(bits.join(' ')||`This profile currently contains limited recorded information for ${p.name}.`)}</p></div><div class="card profile-section"><h2>Life Story</h2><p>${esc(p.biography||'No personal life story has been added yet.').replace(/\n/g,'<br>')}</p></div><div class="card profile-section"><div class="profile-section-head"><h2>Photos <span>${photos.length}</span></h2><a href="/?view=gallery&person=${encodeURIComponent(p.id)}&type=photo">View all</a></div><div class="profile-media-grid">${cards(photos)||'<p class="muted">No photographs have been linked yet.</p>'}</div></div><div class="card profile-section"><div class="profile-section-head"><h2>Documents <span>${documents.length}</span></h2><a href="/?view=gallery&person=${encodeURIComponent(p.id)}&type=document">View all</a></div><div class="profile-media-grid">${cards(documents)||'<p class="muted">No documents have been linked yet.</p>'}</div></div></div></div></section>`;
}
async function treeView(){const ps=await people(),rr=await rels(),by=Object.fromEntries(ps.map(p=>[p.name,p]));const node=(p,cl='')=>p?`<a class="node ${cl}" href="/?view=profile&id=${p.id}"><div class="avatar" style="margin:auto">${esc(initials(p))}</div><strong>${esc(p.name)}</strong><small class="muted">${esc(years(p))}</small></a>`:'';const wm=by['William Metcalfe'],mk=by['Mary Kavanagh'],children=wm?rr.r.filter(x=>x.parent_id===wm.id).map(x=>ps.find(p=>p.id===x.child_id)).filter(Boolean):[],anc=['Anthony Medcalf','Sarah Jane Byrne','Enoch Medcalf','Mary King','Thomas Kavanagh','Anne Carroll','Owen Kavanagh','Elizabeth Kavanagh'].map(n=>by[n]).filter(Boolean);app.innerHTML=header('Family Tree','Explore the generations that came before us.')+`<section class="section"><div class="wrap"><div class="tree-scroll"><div class="tree-stage"><div class="ancestor-row">${anc.slice(0,4).map(p=>node(p)).join('')}</div><div class="connector"></div><div class="parents-row">${node(wm,'parent')}${node(mk,'parent')}</div><div class="connector"></div><div class="rail"></div><div class="children-row">${children.map(p=>`<div class="childwrap">${node(p,p.name==='Catherine Metcalfe'?'central':'')}</div>`).join('')}</div></div></div></div></section>`}
const mobileMenu=document.getElementById('mobileMenu');document.getElementById('menuButton').onclick=()=>mobileMenu.classList.toggle('open');document.getElementById('bottomMenu').onclick=e=>{e.preventDefault();mobileMenu.classList.toggle('open');scrollTo({top:0,behavior:'smooth'})};
(async()=>{try{
  if(view==='home'&&(qs.get('code')||location.hash.includes('access_token='))){
    if(qs.get('code')){const {error}=await db.auth.exchangeCodeForSession(qs.get('code'));if(error)throw error}
    const {data}=await db.auth.getSession();
    if(data.session){location.replace('/?view=admin');return}
  }
  if(view==='tree')await treeView();else if(view==='people')await peopleView();else if(view==='places')await placesView();else if(view==='timeline')await timelineView();else if(view==='stories')await storiesView();else if(view==='records')await recordsView();else if(view==='gallery')await galleryView();else if(view==='profile')await profile();else await home()
}catch(e){console.error(e);app.innerHTML=header('Something went wrong','The family archive could not load this section.')+`<section class="section"><div class="wrap"><div class="status error">${esc(e.message||e)}</div></div></section>`}})();
