const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const variants=s=>{const x=String(s||'').toLowerCase();const out=new Set([x]);if(/metcalf/.test(x)||/medcalf/.test(x))['metcalfe','metcalf','medcalf','medcalfe'].forEach(v=>out.add(v));return [...out]};
const year=s=>+(String(s||'').match(/(?:18|19|20)\d{2}/)||[])[0]||0;
const split=n=>{const p=String(n||'').trim().split(/\s+/);return{first:p.slice(0,-1).join(' '),surname:p.at(-1)||''}};
function score(row,p,relatives){let n=0,reasons=[];const name=split(p.name),rfirst=row.first_name||row.firstname||'',rs=row.surname||'';if(norm(rfirst)===norm(name.first)){n+=35;reasons.push('given name')}else if(norm(rfirst).includes(norm(name.first.split(' ')[0]))){n+=20;reasons.push('similar given name')}if(variants(name.surname).some(v=>norm(rs)===norm(v))){n+=30;reasons.push('surname variant')}const by=year(p.birth_date_text),age=+(row.updated_age||row.age||0);if(by&&age){const expected=1926-by,d=Math.abs(expected-age);if(d<=1){n+=25;reasons.push('age fits birth year')}else if(d<=3){n+=12;reasons.push('age is close')}}const places=[p.birth_place,p.death_place].filter(Boolean).map(norm);const rp=norm([row.county,row.townland,row.ded,row.birthplace_county].filter(Boolean).join(' '));if(places.some(x=>x&&rp.includes(x))){n+=12;reasons.push('place matches')}const relNames=relatives.map(x=>split(x.name).surname).filter(Boolean);if(relNames.some(x=>variants(x).some(v=>norm(rs)===norm(v)))){n+=4}return{score:Math.min(n,100),reasons}}
function label(n){return n>=85?'Strong match':n>=60?'Possible match — review required':'Research lead'}
async function run(){const q=new URLSearchParams(location.search);if(q.get('view')!=='profile'||!q.get('id'))return;const cfg=window.__APP_CONFIG__||{};if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY)return;const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY),id=q.get('id');const [{data:p},{data:pc},{data:rels}]=await Promise.all([db.from('people').select('*').eq('id',id).single(),db.from('parent_child').select('*'),db.from('person_relationships').select('*')]);if(!p)return;const ids=new Set();(pc||[]).forEach(r=>{if(r.parent_id===id)ids.add(r.child_id);if(r.child_id===id)ids.add(r.parent_id)});(rels||[]).forEach(r=>{if(r.person_id===id)ids.add(r.related_person_id);if(r.related_person_id===id)ids.add(r.person_id)});const {data:family}=ids.size?await db.from('people').select('*').in('id',[...ids]):{data:[]};const n=split(p.name),surnameVariants=variants(n.surname),all=[];for(const surname of surnameVariants){try{const r=await fetch(`/api/census1926?first=${encodeURIComponent(n.first.split(' ')[0])}&surname=${encodeURIComponent(surname)}`);if(!r.ok)continue;const data=await r.json(),rows=data.results||data.data||data.records||[];rows.forEach(row=>all.push(row))}catch{}}
const unique=[...new Map(all.map(r=>[r.a_id||JSON.stringify(r),r])).values()].map(r=>({...r,...score(r,p,family||[])})).sort((a,b)=>b.score-a.score).slice(0,8);let tries=0;while(!document.querySelector('.profile-v1-content')&&tries++<40)await new Promise(r=>setTimeout(r,100));const host=document.querySelector('.profile-v1-content');if(!host)return;const section=document.createElement('section');section.id='automatic-record-search';section.className='card profile-panel';section.innerHTML=`<div class="profile-section-head"><div><span class="section-kicker">Automatic evidence search</span><h2>1926 Census candidates</h2></div></div><p class="muted">Searched automatically using the profile name, spelling variants, known dates, places and family context. Missing birth dates reduce confidence but do not prevent a search.</p>${unique.length?`<div class="verified-record-grid">${unique.map(r=>{const url=`https://nationalarchives.ie/collections/search-the-1926-census/census-record/#a_id=${encodeURIComponent(r.a_id||'')}`;return `<article><span class="evidence-badge ${r.score>=85?'evidence-corroborated_family_history':'evidence-research_lead'}">${esc(label(r.score))} · ${r.score}%</span><h3>${esc([r.first_name,r.surname].filter(Boolean).join(' ')||p.name)}</h3><p>${esc([r.updated_age||r.age?`age ${r.updated_age||r.age}`:'',r.relationship_to_head||r.updated_relationship_to_head,r.townland,r.county].filter(Boolean).join(' · '))}</p><p class="muted">Matched on: ${esc(r.reasons.join(', ')||'name')}</p><a class="chapter-record-link" href="${url}" target="_blank" rel="noopener">Review original census record ↗</a></article>`}).join('')}</div>`:'<p>No sufficiently close 1926 candidates were returned. The search still ran; add dates, places or relatives to improve future matching.</p>'}`;const verified=host.querySelector('#verified-records');verified?verified.after(section):host.prepend(section)}
run();
