const cfg=window.__APP_CONFIG__||{};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const publicUrl=m=>`${cfg.SUPABASE_URL}/storage/v1/object/public/${m.bucket_name||'family-media'}/${m.storage_path}`;
const photoCategories=['Portrait','Family / group photo','House / place','Other photo'];
const documentCategories=['Birth record','Baptism record','Marriage record','Death record','Census record','Military record','Newspaper clipping','Will / probate','Other document'];
const categoryOptions=type=>(type==='photo'?photoCategories:documentCategories).map(x=>`<option>${esc(x)}</option>`).join('');
const mediaIcon=m=>m.media_type==='photo'?'🖼️':'📜';

async function load(){
  const [{data:people,error:pe},{data:media,error:me},{data:tags,error:te}]=await Promise.all([
    db.from('people').select('id,name,surname').order('name'),
    db.from('media').select('*').order('created_at',{ascending:false}),
    db.from('media_people').select('media_id,person_id')
  ]);
  if(pe||me||te)throw pe||me||te;
  // Profile photographs already appear on their person's profile. Keeping them
  // out of the main archive prevents the same image looking like a duplicate.
  const ps=people||[],items=(media||[]).filter(item=>!item.is_profile_photo),tagRows=tags||[],byId=Object.fromEntries(ps.map(p=>[p.id,p]));
  const peopleFor=mid=>tagRows.filter(t=>t.media_id===mid).map(t=>byId[t.person_id]).filter(Boolean);

  app.innerHTML=`<section class="heritage"><div class="wrap"><h1>Photos &amp; Documents</h1><p>Photographs, official records and memories preserved together.</p></div></section>
  <section class="section archive-contribute"><div class="wrap"><details class="card upload-card" id="uploadPanel"><summary><span><strong>Add to the family archive</strong><small>Upload a photograph or historical document</small></span><span class="summary-plus" aria-hidden="true">＋</span></summary>
    <form id="archiveUploadForm">
      <div class="form-grid archive-type-row"><div class="field"><label for="mediaType"><strong>What are you uploading?</strong></label><select id="mediaType"><option value="photo">Photo</option><option value="document">Document</option></select></div><div class="field"><label for="mediaCategory"><strong>Category</strong></label><select id="mediaCategory">${categoryOptions('photo')}</select></div></div>
      <label class="file-drop" for="archiveFiles"><span class="file-drop-icon">＋</span><strong id="chooseLabel">Choose photos</strong><span id="acceptHelp">JPG, PNG, WebP or HEIC • up to 10 MB each</span><input id="archiveFiles" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple required></label>
      <div id="fileSummary" class="file-summary muted">No files selected yet.</div>
      <div class="form-grid"><div class="field"><label for="mediaTitle"><strong>Title</strong> <span class="muted">(optional)</span></label><input id="mediaTitle" maxlength="120" placeholder="e.g. William and Mary’s wedding"></div><div class="field"><label for="mediaDate"><strong>Date</strong> <span class="muted">(exact or approximate)</span></label><input id="mediaDate" maxlength="80" placeholder="e.g. June 1958 or circa 1920"></div><div class="field full"><label for="mediaDescription"><strong>Description or memory</strong> <span class="muted">(optional)</span></label><textarea id="mediaDescription" maxlength="1500" placeholder="Add the occasion, place, names or anything remembered..."></textarea></div><div class="field full"><label for="mediaSource"><strong>Source</strong> <span class="muted">(optional)</span></label><input id="mediaSource" maxlength="240" placeholder="e.g. IrishGenealogy.ie, Ancestry or family collection"></div></div>
      <div class="people-picker"><div class="picker-head"><strong id="peoplePrompt">Who is shown?</strong><span class="muted">Link this item to one or more family members. It will appear on every linked profile.</span></div><div id="selectedPeople" class="selected-people" aria-live="polite"></div><div class="autocomplete-wrap"><input id="personSearch" class="person-search" type="search" placeholder="Search family members" autocomplete="off" aria-autocomplete="list" aria-controls="peopleSuggestions"><div id="peopleSuggestions" class="people-suggestions" role="listbox" hidden></div></div><label class="unidentified-check"><input id="unidentified" type="checkbox"> The person or people are not identified yet</label></div>
      <div id="uploadStatus" class="status" hidden></div><button class="btn upload-btn" type="submit">Add to Photos &amp; Documents</button>
    </form>
  </details></div></section>
  <section class="section archive-list"><div class="wrap"><div class="archive-heading"><div><h2>Family Archive</h2><p class="muted" id="resultCount"></p></div><div class="archive-filters"><select id="typeFilter" aria-label="Filter by media type"><option value="all">Photos &amp; documents</option><option value="photo">Photos only</option><option value="document">Documents only</option></select><select id="personFilter" aria-label="Filter by family member"><option value="all">All family members</option><option value="unidentified">Unidentified people</option>${ps.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><input id="archiveSearch" type="search" placeholder="Search title, category or source" aria-label="Search archive"></div></div><div id="archiveGrid" class="archive-grid"></div></div></section>`;

  const type=document.getElementById('mediaType'),category=document.getElementById('mediaCategory'),files=document.getElementById('archiveFiles'),summary=document.getElementById('fileSummary'),search=document.getElementById('personSearch'),suggestions=document.getElementById('peopleSuggestions'),selectedBox=document.getElementById('selectedPeople'),unidentified=document.getElementById('unidentified'),status=document.getElementById('uploadStatus'),form=document.getElementById('archiveUploadForm'),selected=new Set();
  const updateType=()=>{const isPhoto=type.value==='photo';category.innerHTML=categoryOptions(type.value);files.accept=isPhoto?'image/jpeg,image/png,image/webp,image/heic,image/heif':'application/pdf,image/jpeg,image/png,image/webp';document.getElementById('chooseLabel').textContent=isPhoto?'Choose photos':'Choose documents';document.getElementById('acceptHelp').textContent=isPhoto?'JPG, PNG, WebP or HEIC • up to 10 MB each':'PDF, JPG, PNG or WebP • up to 10 MB each';document.getElementById('peoplePrompt').textContent=isPhoto?'Who is shown?':'Who does this document relate to?';summary.textContent='No files selected yet.';files.value=''};
  type.addEventListener('change',updateType);
  files.addEventListener('change',()=>{const fs=[...files.files];summary.textContent=fs.length?`${fs.length} file${fs.length===1?'':'s'} selected: ${fs.map(f=>f.name).join(', ')}`:'No files selected yet.'});
  const renderSelected=()=>{selectedBox.innerHTML=[...selected].map(id=>`<button type="button" class="person-chip" data-remove="${esc(id)}"><span>${esc(byId[id]?.name||'Family member')}</span><b aria-hidden="true">×</b></button>`).join('');selectedBox.hidden=selected.size===0};
  const showMatches=()=>{const q=search.value.trim().toLowerCase(),matches=ps.filter(p=>!selected.has(p.id)&&(!q||p.name.toLowerCase().includes(q)));suggestions.innerHTML=matches.length?matches.map(p=>`<button type="button" class="person-suggestion" data-person-id="${esc(p.id)}" role="option"><span class="suggestion-avatar">${esc(p.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase())}</span><span>${esc(p.name)}</span></button>`).join(''):'<div class="no-suggestions">No matching family member</div>';suggestions.hidden=false};
  search.addEventListener('input',showMatches);search.addEventListener('focus',showMatches);search.addEventListener('blur',()=>setTimeout(()=>suggestions.hidden=true,150));
  suggestions.addEventListener('click',e=>{const b=e.target.closest('[data-person-id]');if(!b)return;selected.add(b.dataset.personId);unidentified.checked=false;search.value='';renderSelected();suggestions.hidden=true});
  selectedBox.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;selected.delete(b.dataset.remove);renderSelected()});
  unidentified.addEventListener('change',()=>{if(unidentified.checked){selected.clear();renderSelected()}});

  const renderArchive=()=>{const typeValue=document.getElementById('typeFilter').value,personValue=document.getElementById('personFilter').value,q=document.getElementById('archiveSearch').value.trim().toLowerCase();const filtered=items.filter(m=>{const linked=peopleFor(m.id);return(typeValue==='all'||m.media_type===typeValue)&&(personValue==='all'||(personValue==='unidentified'?m.is_unidentified:linked.some(p=>p.id===personValue)))&&(!q||[m.title,m.description,m.category,m.source_text,m.event_date_text,...linked.map(p=>p.name)].some(v=>String(v||'').toLowerCase().includes(q)))});document.getElementById('resultCount').textContent=`${filtered.length} archived item${filtered.length===1?'':'s'}`;document.getElementById('archiveGrid').innerHTML=filtered.map(m=>{const linked=peopleFor(m.id),u=publicUrl(m),isPhoto=m.media_type==='photo';return `<article class="card archive-item"><a class="archive-preview ${isPhoto?'photo':'document'}" target="_blank" rel="noopener" href="${u}">${isPhoto?`<img src="${u}" alt="${esc(m.title||'Family photograph')}" loading="lazy">`:`<span>📜</span><strong>View document</strong>`}</a><div class="archive-body"><div class="archive-kicker"><span>${mediaIcon(m)} ${esc(m.category||m.media_type)}</span>${m.event_date_text?`<time>${esc(m.event_date_text)}</time>`:''}</div><h3>${esc(m.title||m.original_filename||(isPhoto?'Family photograph':'Family document'))}</h3>${m.description?`<p>${esc(m.description)}</p>`:''}${linked.length?`<div class="archive-people">${linked.map(p=>`<a href="/?view=profile&id=${encodeURIComponent(p.id)}">${esc(p.name)}</a>`).join('')}</div>`:m.is_unidentified?'<div class="archive-people"><span>Unidentified people</span></div>':''}${m.source_text?`<p class="archive-source"><strong>Source:</strong> ${esc(m.source_text)}</p>`:''}</div></article>`}).join('')||'<div class="card archive-empty">No archive items match these filters.</div>'};
  ['typeFilter','personFilter','archiveSearch'].forEach(id=>document.getElementById(id).addEventListener(id==='archiveSearch'?'input':'change',renderArchive));
  const archiveParams=new URLSearchParams(location.search),requestedType=archiveParams.get('type'),requestedPerson=archiveParams.get('person');if(['photo','document'].includes(requestedType))document.getElementById('typeFilter').value=requestedType;if(ps.some(p=>p.id===requestedPerson))document.getElementById('personFilter').value=requestedPerson;renderArchive();

  form.addEventListener('submit',async e=>{e.preventDefault();const chosen=[...selected],fs=[...files.files],isUnknown=unidentified.checked;if(!fs.length){status.hidden=false;status.className='status error';status.textContent='Please choose at least one file.';return}if(!chosen.length&&!isUnknown){status.hidden=false;status.className='status error';status.textContent='Select at least one family member, or mark the people as unidentified.';return}for(const f of fs){if(f.size>10*1024*1024){status.hidden=false;status.className='status error';status.textContent=`${f.name} is larger than 10 MB.`;return}}const btn=form.querySelector('button[type="submit"]');btn.disabled=true;status.hidden=false;status.className='status';status.textContent='Adding files to the family archive…';try{for(const f of fs){const ext=(f.name.split('.').pop()||(type.value==='photo'?'jpg':'pdf')).toLowerCase().replace(/[^a-z0-9]/g,''),kind=type.value==='photo'?'photos':'documents',owner=isUnknown?'unidentified':chosen.length>1?'group':`people/${chosen[0]}`,path=`public-contributions/${kind}/${owner}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await db.storage.from('family-contributions').upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(ue)throw ue;const {data:m,error:ie}=await db.from('media').insert({person_id:chosen[0]||null,media_type:type.value,category:category.value,title:document.getElementById('mediaTitle').value.trim()||null,description:document.getElementById('mediaDescription').value.trim()||null,event_date_text:document.getElementById('mediaDate').value.trim()||null,source_text:document.getElementById('mediaSource').value.trim()||null,storage_path:path,bucket_name:'family-contributions',mime_type:f.type||null,original_filename:f.name,is_unidentified:isUnknown,is_profile_photo:false}).select('id').single();if(ie)throw ie;if(chosen.length){const {error:tagError}=await db.from('media_people').insert(chosen.map(person_id=>({media_id:m.id,person_id})));if(tagError)throw tagError}}status.className='status';status.textContent='Files added successfully. Refreshing the archive…';setTimeout(()=>location.reload(),700)}catch(err){console.error(err);status.className='status error';status.textContent=`Upload failed: ${err.message||err}`;btn.disabled=false}});
}

const mobileMenu=document.getElementById('mobileMenu');document.getElementById('menuButton').onclick=()=>mobileMenu.classList.toggle('open');document.getElementById('bottomMenu').onclick=e=>{e.preventDefault();mobileMenu.classList.toggle('open');scrollTo({top:0,behavior:'smooth'})};
load().catch(e=>{console.error(e);app.innerHTML=`<section class="heritage"><div class="wrap"><h1>Photos &amp; Documents</h1><p>The family archive could not load.</p></div></section><section class="section"><div class="wrap"><div class="status error">${esc(e.message||e)}</div></div></section>`});
