const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cleanName=value=>String(value||'').replace(/\//g,'').replace(/\s+/g,' ').trim();
const norm=value=>cleanName(value).toLowerCase().replace(/[^a-z0-9]/g,'');
const year=value=>(String(value||'').match(/(?:17|18|19|20)\d{2}/)||[])[0]||'';
const slug=value=>cleanName(value).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'family-member';

export function parseGedcom(text){
  const people=new Map(),families=new Map();let current=null,event=null;
  for(const raw of String(text||'').split(/\r?\n/)){const match=raw.match(/^(\d+)\s+(?:(@[^@]+@)\s+)?([A-Z0-9_]+)(?:\s+(.*))?$/i);if(!match)continue;const level=Number(match[1]),xref=match[2]||'',tag=match[3].toUpperCase(),value=(match[4]||'').trim();
    if(level===0){event=null;if(tag==='INDI'&&xref){current={kind:'person',xref,name:'',given_names:'',surname:'',birth_date_text:'',birth_place:'',death_date_text:'',death_place:''};people.set(xref,current)}else if(tag==='FAM'&&xref){current={kind:'family',xref,husband:'',wife:'',children:[],marriage_date_text:'',marriage_place:''};families.set(xref,current)}else current=null;continue}
    if(!current)continue;
    if(current.kind==='person'){if(level===1&&tag==='NAME')current.name=cleanName(value);else if(level===1&&tag==='GIVN')current.given_names=cleanName(value);else if(level===1&&tag==='SURN')current.surname=cleanName(value);else if(level===1&&(tag==='BIRT'||tag==='DEAT'))event=tag;else if(level===2&&event==='BIRT'&&tag==='DATE')current.birth_date_text=value;else if(level===2&&event==='BIRT'&&tag==='PLAC')current.birth_place=value;else if(level===2&&event==='DEAT'&&tag==='DATE')current.death_date_text=value;else if(level===2&&event==='DEAT'&&tag==='PLAC')current.death_place=value}
    if(current.kind==='family'){if(level===1&&tag==='HUSB')current.husband=value;else if(level===1&&tag==='WIFE')current.wife=value;else if(level===1&&tag==='CHIL')current.children.push(value);else if(level===1&&tag==='MARR')event='MARR';else if(level===2&&event==='MARR'&&tag==='DATE')current.marriage_date_text=value;else if(level===2&&event==='MARR'&&tag==='PLAC')current.marriage_place=value}
  }
  for(const person of people.values()){if(!person.name)person.name=[person.given_names,person.surname].filter(Boolean).join(' ');if(!person.given_names||!person.surname){const parts=person.name.split(/\s+/);person.given_names||=parts.slice(0,-1).join(' ');person.surname||=parts.at(-1)||''}}
  return{people,families};
}

function selectedFamily(parsed,rootXref){const selected=new Set([rootXref]),parentFamilies=new Map();for(const family of parsed.families.values())for(const child of family.children)(parentFamilies.get(child)||parentFamilies.set(child,[]).get(child)).push(family);for(const family of parentFamilies.get(rootXref)||[])for(const child of family.children)selected.add(child);const climb=xref=>{for(const family of parentFamilies.get(xref)||[])for(const parent of [family.husband,family.wife].filter(Boolean))if(!selected.has(parent)){selected.add(parent);climb(parent)}};climb(rootXref);return selected}
function proposedImport(parsed,rootXref,currentPeople){const selected=selectedFamily(parsed,rootXref),byXref=new Map(currentPeople.filter(p=>p.gedcom_xref).map(p=>[p.gedcom_xref,p])),byIdentity=new Map();for(const p of currentPeople){const key=`${norm(p.name)}|${year(p.birth_date_text)}`;(byIdentity.get(key)||byIdentity.set(key,[]).get(key)).push(p)}const proposals=[],usedIds=new Set(currentPeople.map(p=>p.id));for(const xref of selected){const incoming=parsed.people.get(xref);if(!incoming)continue;const identity=`${norm(incoming.name)}|${year(incoming.birth_date_text)}`,candidates=byIdentity.get(identity)||[],existing=byXref.get(xref)||(candidates.length===1?candidates[0]:null);let id=existing?.id||`${slug(incoming.name)}-${xref.replace(/\D/g,'').slice(-7)||Math.random().toString(36).slice(2,8)}`;while(usedIds.has(id)&&id!==existing?.id)id+=`-new`;usedIds.add(id);const fields={gedcom_xref:xref,name:incoming.name,given_names:incoming.given_names||null,surname:incoming.surname||null,birth_date_text:incoming.birth_date_text||null,birth_place:incoming.birth_place||null,death_date_text:incoming.death_date_text||null,death_place:incoming.death_place||null},changes={};for(const [key,value] of Object.entries(fields))if(value&&String(existing?.[key]||'')!==String(value))changes[key]={from:existing?.[key]||'',to:value};proposals.push({xref,id,incoming,existing,fields,changes,ambiguous:!existing&&candidates.length>1})}return{selected,proposals}}

export function mountGedcomImporter(container,{db,people,session}){let parsed=null,preview=null,fileName='';container.innerHTML=`<section class="card gedcom-admin"><div class="admin-editor-head"><div><span class="source-type">Ancestry updates</span><h2>Import a GEDCOM update</h2><p class="muted">Upload a fresh Ancestry export. Existing photos, stories, documents and research sources are left untouched.</p></div></div><div class="gedcom-steps"><div><strong>1. Choose exported file</strong><input id="gedcomFile" type="file" accept=".ged,.gedcom,text/plain"></div><div><strong>2. Confirm Catherine</strong><select id="gedcomRoot" disabled><option>Upload a file first</option></select></div><button id="previewGedcom" class="admin-secondary" type="button" disabled>Compare with website</button></div><div id="gedcomStatus" class="status" hidden></div><div id="gedcomPreview"></div></section>`;
  const file=container.querySelector('#gedcomFile'),root=container.querySelector('#gedcomRoot'),button=container.querySelector('#previewGedcom'),status=container.querySelector('#gedcomStatus'),output=container.querySelector('#gedcomPreview');
  file.onchange=async()=>{const selected=file.files?.[0];if(!selected)return;fileName=selected.name;status.hidden=false;status.className='status';status.textContent='Reading GEDCOM…';try{parsed=parseGedcom(await selected.text());if(!parsed.people.size)throw new Error('No people were found in this GEDCOM file.');const likely=[...parsed.people.values()].filter(p=>/catherine/i.test(p.given_names||p.name)&&/metcalfe/i.test(p.surname||p.name)),choices=likely.length?likely:[...parsed.people.values()].filter(p=>/metcalfe/i.test(p.surname||p.name));root.innerHTML=choices.map(p=>`<option value="${esc(p.xref)}">${esc(p.name)}${p.birth_date_text?` — ${esc(p.birth_date_text)}`:''}</option>`).join('');root.disabled=!choices.length;button.disabled=!choices.length;status.textContent=`Read ${parsed.people.size} people and ${parsed.families.size} families. ${likely.length?'Catherine Metcalfe was selected automatically.':'Please select the correct Metcalfe starting person.'}`;output.innerHTML=''}catch(error){parsed=null;root.disabled=true;button.disabled=true;status.className='status error';status.textContent=error.message}};
  button.onclick=()=>{preview=proposedImport(parsed,root.value,people);const additions=preview.proposals.filter(p=>!p.existing&&!p.ambiguous),updates=preview.proposals.filter(p=>p.existing&&Object.keys(p.changes).length),unchanged=preview.proposals.filter(p=>p.existing&&!Object.keys(p.changes).length),ambiguous=preview.proposals.filter(p=>p.ambiguous);output.innerHTML=`<div class="gedcom-summary"><span><strong>${additions.length}</strong> new people</span><span><strong>${updates.length}</strong> updated people</span><span><strong>${unchanged.length}</strong> unchanged</span><span class="${ambiguous.length?'warning':''}"><strong>${ambiguous.length}</strong> possible duplicates</span></div>${ambiguous.length?'<div class="status error">Possible duplicates need to be resolved before this import can proceed.</div>':''}<div class="gedcom-changes">${[...additions,...updates].map(p=>`<article><strong>${esc(p.incoming.name)}</strong><small>${p.existing?'Update existing profile':'Add new family member'}</small>${Object.entries(p.changes).map(([key,value])=>`<span><b>${esc(key.replaceAll('_',' '))}:</b> ${value.from?`<del>${esc(value.from)}</del> → `:''}${esc(value.to)}</span>`).join('')}</article>`).join('')||'<p class="muted">The website already matches this GEDCOM selection.</p>'}</div>${additions.length||updates.length?`<label class="gedcom-confirm"><input id="confirmGedcom" type="checkbox"> I have reviewed these additions and changes.</label><button id="applyGedcom" class="btn" type="button" disabled>Import ${additions.length+updates.length} changes</button>`:''}`;const confirm=output.querySelector('#confirmGedcom'),apply=output.querySelector('#applyGedcom');if(confirm&&apply){confirm.onchange=()=>apply.disabled=!confirm.checked||ambiguous.length>0;apply.onclick=()=>applyImport(additions,updates)}};
  async function applyImport(additions,updates){const apply=output.querySelector('#applyGedcom');apply.disabled=true;status.hidden=false;status.className='status';status.textContent='Importing reviewed changes…';try{if(additions.length){const rows=additions.map(p=>({id:p.id,...p.fields,initials:p.incoming.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase(),relation_label:'Family member',family_line:/kavanagh/i.test(p.incoming.surname)?'Kavanagh':'Metcalfe'}));const {error}=await db.from('people').insert(rows);if(error)throw error}for(const p of updates){const payload=Object.fromEntries(Object.entries(p.changes).map(([key,value])=>[key,value.to]));payload.updated_at=new Date().toISOString();const {error}=await db.from('people').update(payload).eq('id',p.id);if(error)throw error}const idByXref=new Map(preview.proposals.map(p=>[p.xref,p.id])),parentRows=[],coupleRows=[];for(const family of parsed.families.values()){for(const child of family.children)for(const parent of [family.husband,family.wife].filter(Boolean))if(idByXref.has(child)&&idByXref.has(parent))parentRows.push({parent_id:idByXref.get(parent),child_id:idByXref.get(child),parent_role:parent===family.husband?'father':parent===family.wife?'mother':'parent'});if(idByXref.has(family.husband)&&idByXref.has(family.wife))coupleRows.push({person1_id:idByXref.get(family.husband),person2_id:idByXref.get(family.wife),marriage_date_text:family.marriage_date_text||null,marriage_place:family.marriage_place||null})}if(parentRows.length){const {error}=await db.from('parent_child').upsert(parentRows,{onConflict:'parent_id,child_id',ignoreDuplicates:true});if(error)throw error}const {data:existingCouples,error:coupleReadError}=await db.from('couples').select('person1_id,person2_id');if(coupleReadError)throw coupleReadError;const pairKey=(a,b)=>[a,b].sort().join('|'),existingPairs=new Set((existingCouples||[]).map(x=>pairKey(x.person1_id,x.person2_id))),newCouples=coupleRows.filter(x=>!existingPairs.has(pairKey(x.person1_id,x.person2_id)));if(newCouples.length){const {error}=await db.from('couples').insert(newCouples);if(error)throw error}await db.from('gedcom_imports').insert({file_name:fileName,root_xref:root.value,imported_by:session.user.email||null,summary:{new_people:additions.length,updated_people:updates.length,parent_links:parentRows.length,couples:newCouples.length}});status.textContent='GEDCOM update imported successfully. Reloading the Admin area…';setTimeout(()=>location.reload(),1200)}catch(error){apply.disabled=false;status.className='status error';status.textContent=`Import stopped: ${error.message||error}`}}
}
