const cfg=window.__APP_CONFIG__||{};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=window.__SUPABASE_CLIENT__;
const mobileMenu=document.getElementById('mobileMenu');
document.getElementById('menuButton').onclick=()=>mobileMenu.classList.toggle('open');
document.getElementById('bottomMenu').onclick=e=>{e.preventDefault();mobileMenu.classList.toggle('open');scrollTo({top:0,behavior:'smooth'})};

async function load(){
  const {data:entries,error}=await db.from('guestbook_entries').select('id,visitor_name,family_connection,family_branch,visitor_location,message,public_contact_details,created_at').eq('status','approved').order('created_at',{ascending:false});
  if(error)throw error;
  const rows=entries||[];
  const entryCard=e=>`<article class="card ledger-entry" data-entry-id="${esc(e.id)}"><blockquote>${esc(e.message)}</blockquote><footer><strong>${esc(e.visitor_name)}</strong><span>${esc([e.family_connection,e.family_branch,e.visitor_location].filter(Boolean).join(' • '))}</span>${e.public_contact_details?`<span class="public-contact"><strong>Contact:</strong> ${esc(e.public_contact_details)}</span>`:''}<span>${new Date(e.created_at).toLocaleDateString('en-IE',{day:'numeric',month:'long',year:'numeric'})}</span></footer></article>`;
  app.innerHTML=`<section class="heritage"><div class="wrap"><h1>Visitors’ Book</h1><p>Leave your name, connection or a family memory.</p></div></section><section class="section"><div class="wrap visitors-layout"><div class="visitor-ledger"><div class="card visitor-intro"><h2>Welcome to our family history</h2><p>If you recognise a name, share a connection or simply enjoyed visiting, we would love to hear from you.</p></div><div class="ledger-list">${rows.map(entryCard).join('')||'<div class="card ledger-empty"><h2>Be the first to sign</h2><p class="muted">Messages from family and visitors will appear here.</p></div>'}</div></div><form id="visitorForm" class="card visitor-form"><h2>Sign the Visitors’ Book</h2><p class="muted">Your entry will appear as soon as you submit it.</p><div class="form-grid"><div class="field full"><label for="visitorName"><strong>Your name</strong></label><input id="visitorName" minlength="2" maxlength="80" required></div><div class="field"><label for="familyBranch"><strong>Family branch</strong></label><select id="familyBranch"><option>Both / not sure</option><option>Metcalfe</option><option>Kavanagh</option><option>Friend / site visitor</option></select></div><div class="field"><label for="visitorLocation"><strong>Location</strong> <span class="muted">(optional)</span></label><input id="visitorLocation" maxlength="120" placeholder="e.g. Dublin or Manchester"></div><div class="field full"><label for="familyConnection"><strong>Your family connection</strong> <span class="muted">(optional)</span></label><input id="familyConnection" maxlength="160" placeholder="e.g. Granddaughter of… or researching the family"></div><div class="field full"><label for="visitorMessage"><strong>Message or memory</strong></label><textarea id="visitorMessage" minlength="2" maxlength="1000" required placeholder="Share a greeting, connection or family memory..."></textarea></div><div class="visitor-honeypot" aria-hidden="true"><label for="visitorWebsite">Website</label><input id="visitorWebsite" tabindex="-1" autocomplete="off"></div></div><p class="visitor-privacy">Your entry is published immediately. To contact the site owner directly, please use the <a href="/?view=about">About &amp; Contact</a> page.</p><div id="visitorStatus" class="status" hidden></div><button class="btn" type="submit">Sign the Visitors’ Book</button></form></div></section>`;
  const form=document.getElementById('visitorForm'),status=document.getElementById('visitorStatus');
  form.addEventListener('submit',async e=>{e.preventDefault();status.hidden=false;if(document.getElementById('visitorWebsite').value){status.textContent='Thank you. Your entry has been received.';form.reset();return}const button=form.querySelector('button[type="submit"]');button.disabled=true;status.className='status';status.textContent='Publishing your entry…';const id=crypto.randomUUID(),payload={id,visitor_name:document.getElementById('visitorName').value.trim(),family_branch:document.getElementById('familyBranch').value,visitor_location:document.getElementById('visitorLocation').value.trim()||null,family_connection:document.getElementById('familyConnection').value.trim()||null,message:document.getElementById('visitorMessage').value.trim(),status:'approved'};const {data:published,error:entryError}=await db.from('guestbook_entries').insert(payload).select('id,visitor_name,family_connection,family_branch,visitor_location,message,public_contact_details,created_at').single();if(entryError){status.className='status error';status.textContent='Your entry could not be published just now. Please try again.';button.disabled=false;return}fetch('/api/submission-notification',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'visitor_book',id:published.id,name:published.visitor_name,familyBranch:published.family_branch,location:published.visitor_location,familyConnection:published.family_connection,message:published.message})}).catch(()=>{});form.reset();const list=document.querySelector('.ledger-list'),empty=list.querySelector('.ledger-empty');if(empty)empty.remove();list.insertAdjacentHTML('afterbegin',entryCard(published));status.textContent='Thank you — your entry is now published and appears in the Visitors’ Book.';button.disabled=false});
}

load().catch(e=>{console.error(e);app.innerHTML=`<section class="heritage"><div class="wrap"><h1>Visitors’ Book</h1><p>Family connections and messages.</p></div></section><section class="section"><div class="wrap"><div class="status error">${esc(e.message||e)}</div></div></section>`});
